simplify the hooks

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -19,8 +19,11 @@
 # This sample shows how to prevent push of commits where the log message starts
 # with "WIP" (work in progress).
 
-echo "starting pre-push hook"
-make clean dist
+echo >&2 "starting pre-push hook"
+if [ -n $(make clean dist)] then
+	echo >&2 "Can't build, not pushing"
+	exit 1
+fi
 
 remote="$1"
 url="$2"
